
----------------SQL PRACTICES----------

SELECT JOB_TITLE
FROM JOBS
WHERE JOB_TITLE = 'President' OR JOB_TITLE = 'Sales Manager'
   OR JOB_TITLE = 'Finance Manager';

SELECT JOB_TITLE
FROM JOBS
WHERE JOB_TITLE IN ('President', 'Sales Manager', 'Finance Manager');




SELECT COUNTRY_NAME
FROM COUNTRIES
WHERE COUNTRY_NAME != 'USA' AND COUNTRY_NAME != 'Canada';

SELECT COUNTRY_NAME
FROM COUNTRIES
WHERE COUNTRY_NAME NOT IN ('USA', 'Canada');

SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE SALARY BETWEEN 3000 AND 10000;

SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE SALARY >= 3000 AND SALARY <= 10000;

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID is null;

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID is not null;

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'C%';

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '__z__';

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '_u%';

SELECT SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC ;

SELECT *
FROM EMPLOYEES
ORDER BY FIRST_NAME ASC, LAST_NAME DESC ;







